/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   test_validation.h                                  :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: thaperei <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/04/11 08:54:36 by thaperei          #+#    #+#             */
/*   Updated: 2026/04/15 19:42:50 by thaperei         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef TEST_VALIDATION_H
# define TEST_VALIDATION_H

void test_valid_extension(void **state);
void test_invalid_extension(void **state);
void test_split_spaces(void **state);
// Validate ft_split_charset
void test_split_charset_basic(void **state);
void test_split_charset_single_word(void **state);
void test_split_charset_no_delimiter_in_string(void **state);
void test_split_charset_only_delimiters(void **state);
void test_split_charset_empty_string(void **state);
void test_split_charset_empty_charset(void **state);
void test_split_charset_null_string(void **state);
void test_split_charset_null_charset(void **state);
void test_split_charset_leading_delimiters(void **state);
void test_split_charset_trailing_delimiters(void **state);
void test_split_charset_consecutive_delimiters(void **state);
void test_split_charset_multiple_delimiters_in_charset(void **state);
void test_split_charset_single_char_words(void **state);
void test_split_charset_result_null_terminated(void **state);
void test_split_charset_word_count(void **state);
void test_split_charset_delimiter_space_and_tab(void **state);
void test_split_charset_delimiter_comma_and_semicolon(void **state);
void test_split_charset_single_char_string(void **state);
void test_split_charset_single_char_is_delimiter(void **state);
void test_split_charset_all_same_delimiter(void **state);
// Validate File
void test_read_file_valid(void **state);
void test_valid_real_inputs(void **state);
void test_read_file_invalid(void **state);
void test_read_file_empty(void **state);
// Validate float string
void test_valid_float_integer(void **state);
void test_valid_float_positive(void **state);
void test_valid_float_negative(void **state);
void test_valid_float_explicit_plus(void **state);
void test_valid_float_leading_dot(void **state);
void test_valid_float_trailing_dot(void **state);
void test_valid_float_only_dot(void **state);
void test_valid_float_only_sign(void **state);
void test_valid_float_null(void **state);
void test_valid_float_empty(void **state);
void test_valid_float_non_numeric(void **state);
void test_valid_float_scientific(void **state);
void test_valid_float_spaces(void **state);
void test_valid_float_multiple_dots(void **state);
// Validate int string
void test_valid_int_positive(void **state);
void test_valid_int_zero(void **state);
void test_valid_int_null(void **state);
void test_valid_int_empty(void **state);
void test_valid_int_negative(void **state);
void test_valid_int_explicit_plus(void **state);
void test_valid_int_with_newline(void **state);
void test_valid_int_double_newline(void **state);
void test_valid_int_non_numeric(void **state);
void test_valid_int_float(void **state);
void test_valid_int_max_int(void **state);
void test_valid_int_leading_zeros(void **state);
void test_valid_int_alphanumeric(void **state);
void test_valid_int_only_newline_after_digits(void **state);
// Validate Ratio
void test_valid_ratio_zero(void **state);
void test_valid_ratio_one(void **state);
void test_valid_ratio_mid(void **state);
void test_valid_ratio_negative(void **state);
void test_valid_ratio_above_one(void **state);
void test_valid_ratio_null(void **state);
void test_valid_ratio_non_numeric(void **state);
void test_valid_ratio_empty_string(void **state);
// Validate Color
void test_valid_color_valid(void **state);
void test_valid_color_null(void **state);
void test_valid_color_too_few_components(void **state);
void test_valid_color_too_many_components(void **state);
void test_valid_color_out_of_range_high(void **state);
void test_valid_color_out_of_range_low(void **state);
void test_valid_color_boundary_zero(void **state);
void test_valid_color_boundary_max(void **state);
void test_valid_color_non_numeric(void **state);
void test_valid_color_empty_string(void **state);
// Validate Coordinates
void test_valid_coordinates_valid(void **state);
void test_valid_coordinates_valid_int_values(void **state);
void test_valid_coordinates_null(void **state);
void test_valid_coordinates_too_few(void **state);
void test_valid_coordinates_too_many(void **state);
void test_valid_coordinates_negative(void **state);
void test_valid_coordinates_without_decimal(void **state);
void test_valid_coordinates_decimal(void **state);
void test_valid_coordinates_numeric_with_non_numeric(void **state);
void test_valid_coordinates_non_numeric(void **state);
void test_valid_coordinates_empty_string(void **state);
// Validate normal vector
void test_valid_normalized_vector_valid(void **state);
void test_valid_normalized_vector_null(void **state);
void test_valid_normalized_vector_empty(void **state);
void test_valid_normalized_vector_too_few(void **state);
void test_valid_normalized_vector_too_many(void **state);
void test_valid_normalized_vector_out_of_range(void **state);
void test_valid_normalized_vector_boundary_min(void **state);
void test_valid_normalized_vector_boundary_max(void **state);
void test_valid_normalized_vector_non_numeric(void **state);
// Validate fov
void test_valid_fov_valid(void **state);
void test_valid_fov_null(void **state);
void test_valid_fov_empty(void **state);
void test_valid_fov_boundary_zero(void **state);
void test_valid_fov_boundary_max(void **state);
void test_valid_fov_out_of_range(void **state);
void test_valid_fov_negative(void **state);
void test_valid_fov_float(void **state);
void test_valid_fov_non_numeric(void **state);
// Validate ambient
void test_valid_ambient_valid(void **state);
void test_valid_ambient_null_arr(void **state);
void test_valid_ambient_invalid_ratio(void **state);
void test_valid_ambient_invalid_color(void **state);
void test_valid_ambient_both_invalid(void **state);
void test_valid_ambient_boundary_ratio_zero(void **state);
void test_valid_ambient_boundary_ratio_one(void **state);
void test_valid_ambient_boundary_color_max(void **state);
void test_duplicate_ambient(void **state);
// Validate Camera
void test_valid_camera_valid(void **state);
void test_valid_camera_null_arr(void **state);
void test_valid_camera_null_first_element(void **state);
void test_valid_camera_invalid_coordinates(void **state);
void test_valid_camera_invalid_vector(void **state);
void test_valid_camera_invalid_fov(void **state);
void test_valid_camera_all_invalid(void **state);
void test_valid_camera_boundary_fov_zero(void **state);
void test_valid_camera_boundary_fov_max(void **state);
void test_valid_camera_fov_out_of_range(void **state);
void test_valid_camera_vector_boundary(void **state);
void test_valid_camera_vector_non_numeric(void **state);
void test_valid_camera_fov_float(void **state);
void test_valid_camera_fov_negative(void **state);
// Validate Light
void test_valid_light_valid(void **state);
void test_valid_light_null_arr(void **state);
void test_valid_light_null_first_element(void **state);
void test_valid_light_invalid_coordinates(void **state);
void test_valid_light_invalid_ratio(void **state);
void test_valid_light_invalid_color(void **state);
void test_valid_light_all_invalid(void **state);
void test_valid_light_boundary_ratio_zero(void **state);
void test_valid_light_boundary_ratio_one(void **state);
void test_valid_light_boundary_color_max(void **state);
void test_valid_light_ratio_above_one(void **state);
void test_valid_light_color_out_of_range(void **state);
void test_valid_light_coordinates_wrong_count(void **state);
void test_valid_light_null_coordinates(void **state);
// Validate sphere
void test_valid_sphere_valid(void **state);
void test_valid_sphere_null_arr(void **state);
void test_valid_sphere_invalid_coordinates(void **state);
void test_valid_sphere_invalid_diameter(void **state);
void test_valid_sphere_invalid_color(void **state);
void test_valid_sphere_all_invalid(void **state);
void test_valid_sphere_negative_diameter(void **state);
void test_valid_sphere_zero_diameter(void **state);
void test_valid_sphere_null_coordinates(void **state);
void test_valid_sphere_null_color(void **state);
// Validate plane
void test_valid_plane_valid(void **state);
void test_valid_plane_null_arr(void **state);
void test_valid_plane_null_first_element(void **state);
void test_valid_plane_null_coordinates(void **state);
void test_valid_plane_null_vector(void **state);
void test_valid_plane_null_color(void **state);
void test_valid_plane_invalid_coordinates(void **state);
void test_valid_plane_invalid_vector(void **state);
void test_valid_plane_invalid_color(void **state);
void test_valid_plane_all_invalid(void **state);
void test_valid_plane_vector_out_of_range(void **state);
void test_valid_plane_vector_boundary_min(void **state);
void test_valid_plane_vector_boundary_max(void **state);
void test_valid_plane_color_boundary_zero(void **state);
void test_valid_plane_color_boundary_max(void **state);
void test_valid_plane_coordinates_wrong_count(void **state);
void test_valid_plane_vector_wrong_count(void **state);
// Validate cylinder
void test_valid_cylinder_valid(void **state);
void test_valid_cylinder_null_arr(void **state);
void test_valid_cylinder_null_coordinates(void **state);
void test_valid_cylinder_null_vector(void **state);
void test_valid_cylinder_null_diameter(void **state);
void test_valid_cylinder_null_height(void **state);
void test_valid_cylinder_null_color(void **state);
void test_valid_cylinder_invalid_coordinates(void **state);
void test_valid_cylinder_invalid_vector(void **state);
void test_valid_cylinder_invalid_diameter(void **state);
void test_valid_cylinder_invalid_height(void **state);
void test_valid_cylinder_invalid_color(void **state);
void test_valid_cylinder_all_invalid(void **state);
void test_valid_cylinder_negative_diameter(void **state);
void test_valid_cylinder_zero_diameter(void **state);
void test_valid_cylinder_negative_height(void **state);
void test_valid_cylinder_zero_height(void **state);
void test_valid_cylinder_boundary_diameter(void **state);
void test_valid_cylinder_boundary_height(void **state);
void test_valid_cylinder_vector_out_of_range(void **state);
void test_valid_cylinder_vector_wrong_count(void **state);
void test_valid_cylinder_color_wrong_slot(void **state);
// Validate input
void test_valid_input_valid_scene_with_more_newline(void **state);
void test_valid_input_valid_scene(void **state);
void test_valid_input_null_file(void **state);
void test_valid_input_invalid_extension(void **state);
void test_valid_input_no_extension(void **state);
void test_valid_input_missing_file(void **state);
void test_valid_input_empty_file(void **state);
void test_valid_input_missing_camera_and_light(void **state);
void test_valid_input_duplicate_ambient(void **state);
void test_valid_input_invalid_ambient(void **state);
void test_valid_input_missing_ambient_and_light(void **state);
void test_valid_input_duplicate_camera(void **state);
void test_valid_input_missing_ambient_and_camera(void **state);
void test_valid_input_duplicate_light(void **state);
void test_valid_input_valid_sphere(void **state);
void test_valid_input_invalid_sphere(void **state);
void test_valid_input_valid_plane(void **state);
void test_valid_input_invalid_plane(void **state);
void test_valid_input_valid_cylinder(void **state);
void test_valid_input_invalid_cylinder(void **state);
void test_valid_input_unknown_identifier(void **state);
void test_invalid_identifier(void **state);
void test_wrong_arg_count(void **state);
void test_valid_scene(void **state);
void test_missing_camera(void **state);
#endif
